# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1c95525f-54a3-4275-8b46-c932ba46ad2b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1c95525f-54a3-4275-8b46-c932ba46ad2b".device = "/dev/disk/by-uuid/1c95525f-54a3-4275-8b46-c932ba46ad2b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4256-62C8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-10ef9b73-65b2-4661-ba38-547d6b936ed0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
